### ISSUE TITLE
Problem with 'Panelize'

### ISSUE THREAD

**Issue by mdraven** [MidnightCommander/mc-old#57]
MC forget items in 'Panelize'.

1) Add something to 'Panelize'. It works with 'Find file' and 'External panelize' too.
2) Press C-o several times(or run some console command)
3) Panel is now empty

**Comment by mdraven** [comment]
It is very strange, but bug is only on right panel.
The left panel doesn't forget.

**Comment by mdraven** [comment]
I created a new user and everything works for him without bug.
Now I removed current user's files ".config/mc", ".local/share/mc" and ".cache/mc", but it didn't help.

What to me still to try to make?

**Comment by ghost** [comment]
I confirm this happens to me with these versions of mc:

```
$ /usr/bin/mc -V
GNU Midnight Commander 4.8.13-70-g7695f0a
Built with GLib 2.42.1
Using the S-Lang library with terminfo database
With builtin Editor
With subshell support as default
With support for background operations
With mouse support on xterm
With internationalization support
With multiple codepages support
Virtual File Systems: cpiofs, tarfs, sfs, extfs, ftpfs, sftpfs, fish
Data types: char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64;

...

$ /usr/bin/mc -V
GNU Midnight Commander 4.8.14-3-g7c39038
Built with GLib 2.42.2
Using the S-Lang library with terminfo database
With builtin Editor
With subshell support as default
With support for background operations
With mouse support on xterm
With internationalization support
With multiple codepages support
Virtual File Systems: cpiofs, tarfs, sfs, extfs, ftpfs, sftpfs, fish
Data types: char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64;
```

Sometimes (with the latter mc version) the panel isn't empty but contains one `@bin` symlink whose below status says `<readlink failed>`  then C-o made it a folder `/bin` and status says normally `/bin`  (the status that I'm talking about  is the part which says `UP--DIR` when you're on `..` with the cursor)
The next C-o transforms it in a symlink again and remains a symlink unless I tab to the next pannel and the C-o ....

**Comment by ghost** [comment]
Reproduce:
1. on the left panel, get into a folder which has for example 2 folders which the right panel has: eg. `dev` and `bin`
2. cd /  on the right panel  (because it has `dev` and `bin` folders)
3. make sure left panel and right panel are in different current folders! (but both have (at least) 2 same named folders)
4. put cursor on left panel anywhere
5. Alt+shift+/  to open find file dialog and find \* files recursively starting at .   Using shell paterns
(EDIT: find recursively is not necessary)
6. press l to Panelize
7. press C-o four times
Now what you see on left panel is:

```
@bin
/dev
```

Any number of C-o  at this time will show the same thing, nothing will change!
8. switch to right panel (press tab key)
9. press C-o twice
Observe left panel changed to:

```
/bin
/dev
```

Any amount of C-o at this time will make no further changes, what you see remains.
10. switch to left panel (tab key)
11. press C-o four times
Observe the left panel is back to symlink+folder, as shown in step 7

**Comment by ghost** [comment]
step 12. while in panelize, try to find again - the find from step 5
step 13. panelize the find,
what you see is:

```
~bin
/dev
```

and any amount of C-o will not change the contents.
But if you tab to the right panel, C-o twice will change to:

```
/bin
/dev
```

Going back to left panel and C-o 4 times, changes it back to what I said above in step 13

To get the behaviour in OP, just make sure the right panel doesn't have any common folders with the contents of panelize(on the left panel): now you get empty left panel.

Cheers,

**Comment by zyv** [comment]
http://www.midnight-commander.org/ticket/3489
