### ISSUE TITLE
syntax error in patchfs.in

### ISSUE THREAD

**Issue by zazaho** [MidnightCommander/mc-old#93]
Hello,

After the last commit (support for lzip) patchfs yields an error message. I looked at the code and the reason is that the two elseif statements in patchfs.in are copy pasted in the wrong location.
A simple fix is attached

With kind regards,

Sacha
[mc-syntax-error.patch.txt](https://github.com/MidnightCommander/mc/files/173585/mc-syntax-error.patch.txt)

**Comment by egmontkob** [comment]
Yup... thanks!

@ mc devs :) Given ticket 3611 and this, what do you think about a hotfix followup release (e.g. 4.8.16.1 - is the infrastructure prepared for such version numbers?)?

**Comment by aborodin** [comment]
Thanks!
Created https://www.midnight-commander.org/ticket/3620

**Comment by aborodin** [comment]
Applied as 48cfd3b28d0837ae67aacf7952ac4740423bac0d.

**Comment by zyv** [comment]
@egmontkob I think there shouldn't be any fundamental problems with this version number, but I haven't checked.

I'm not sure about the need for rushing a next release though. The FISH problem is bad; but packages can carry a patch for that, and in fact, the unofficial ones already do. I've also let Jindrich and Dmitri know. The patchfs screwup is also annoying, but same applies here, except that it's an even less used feature, and those who do use it can apply a patch themselves.

What I really feel bad about is that both problems could have been avoided if we had at least some very basic tests both for FISH, which is now basically unmaintainable, because one can't change a single letter there without fear of breaking everything, and patchfs, where a stupid syntax mistake could have been avoided if the syntax was checked.

Now, if we simply commit the patches and close the tickets, exactly the same will happen again and again. Since nobody is testing master, and we don't have enough resources to test it properly, every next release will keep bringing such surprises.

**Comment by zyv** [comment]
@egmontkob I've left a comment at https://www.midnight-commander.org/ticket/3620#comment:5, let's move the discussion there, GitHub is such a pain.
